model_parameters=list()
model_parameters$names                             =c('alpha','beta','lambda1','lambda0')
model_parameters$transformation                    =c('logit','none','none','none')
model_parameters$artificial_population_location    =c(0.5,3,0,0)
model_parameters$artificial_population_scale       =c(1,1.5,1.5,1.5)
